name: Deploy Dashboard
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Inject Secret
        shell: bash
        env:
          API_KEY_SECRET: ${{ secrets.API_KEY }}
        run: |
          sed -i "s/REPLACE_WITH_SECRET_TOKEN/$API_KEY_SECRET/g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
