name: Fetch MTA Data
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:    # Allows you to trigger it manually from the Actions tab
jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Data
        run: |
          curl -H "X-App-Token: ${{ secrets.API_KEY }}" \
          "https://data.ny.gov/resource/t6yz-b64h.json?$limit=100" > data.json
      - name: Commit
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add data.json
          git commit -m "Update MTA data"
          git push
